name: Build Unity Project

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    name: Build for Windows
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Cache Unity
        uses: actions/cache@v3
        with:
          path: ~/.cache/unity
          key: Unity-${{ runner.os }}

      - name: Set up Unity
        uses: game-ci/unity-installer@v2
        with:
          unityVersion: 60000.0.47f1

      - name: Build Project
        uses: game-ci/unity-builder@v2
        with:
          targetPlatform: StandaloneWindows64

      - name: Upload Build
        uses: actions/upload-artifact@v3
        with:
          name: WindowsBuild
          path: build/StandaloneWindows64
